name: lime_english
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.1.0
  font_awesome_flutter: ^10.5.0
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  get_storage: null
  json_annotation: ^4.8.1
  logger: ^2.0.1
  path_provider: ^2.1.0
  photo_view: null
  video_player: ^2.7.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/zh_CN.json
    - assets/images/1.jpg
